---


- hosts: all
  become: true
  tasks:

  - name: yum package updates
    yum:
      allow_downgrade: yes

  - name: install software packages package
    yum:
      name: telnet
      state: latest

  - name: install httpd
    yum:
      name: httpd
      state: latest
