---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: remove telnet package from Ubuntu
    apt: 
      name: telnet
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: remove apache2 and mariadb package from Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - mariadb
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: remove telnet package
    yum:
      name: telnet
      state: absent
    when: ansible_distribution == "CentOS"

  - name: remove apache2 php and mariadb for CentOS
    yum:
      name:
        - httpd
        - php
        - mariadb
      state: absent
    when: ansible_distribution == "CentOS"

  - name: remove samba from CentOS
    yum:
      name: 
        - samba
      state: absent
    when: ansible_distribution == "CentOS"
