---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: update repository index CentOS
    tags: always
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 package Ubuntu
    tags: ubuntu,apache2,apache,telnet
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - telnet
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php CentOS
    tags: centos,apache,httpd
    yum:
      name:
        - httpd
        - php
        - telnet
      state: latest
    when: ansible_distribution == "CentOS"

  - name: copy defualt html file for site
    tags: apache,apache2,https
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip
 
  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.1.9/terraform_1.1.9_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: db_servers
  become: true
  tasks:
 
  - name: install mariadb package CentOS
    tags: centos,db,mariadb,telnet
    yum:
      name: 
         - mariadb-server
         - telnet
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package Ubuntu
    tags: ubuntu,db,mariadb,telnet
    apt:
      name:
         - mariadb-server
         - telnet
      state: latest
    when: ansible_distribution == "Ubuntu"
