---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cahce Ubuntu
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: update repo cache CentOS
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"


- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDEVuNR5WJbjrkleFF+HNvOvqEufA7BBicXwhPsHeB/raGvwXUrj9WGhfX6YXom3QbQNZkvdQX6Y1RkhV8swZLb/TYce8QbSc/Q3i6YdVIlzjcRUhx1o7O5jsrvLlrdK2f1FGDu2w3UKvvV9NnEYyGSthw4QdXbJyXDHCLVMn06QxxhlPKnWL70lbBNEt1xkhZinViBQNv9MRtdI6TK0FI7dE/L9RKZEqZ5RKzTJAuq4EsdMqn+oRp+sSDTGiBoWQt3XYjeCOK27UtDq0dl9iou2VsPp+dl9vHDEFsdFA8bb2sk4+g1T0croxxONtsyA/9Z2wB1kHsGYRO4Dhci6iXybUr0UC+oDmkfruneNc/qfZ5eQ0qHtjIWLbHRz5SjvInWIsL0c9H4FpTfpMqTsm8oHEvs+Jt0uRSodoVNHdir2McOsjVmch5SGKSAH8b5PsxYFL1KH9e1VlR8epgqoWm0GJhbnTHKpijhDCghQ7Gn75Sf/r0ZWN+AsXhxfdnVOKLvXoORlHHkk4lir8ermflkOCxrNnsVrA+43FLI2oXPVhpzvTzHMetD8WWlFz+gj0U8tAUm7B3esrI+ZqQgJAna7cIIWTUYV0bdh+pNUk2I2jP0UIjgd6wAY1fDEJYpksVhHN+jOWkArwXhw0OljzYBi8+pY8a4+cOTNPx4HtflQQ== ansible1"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 package Ubuntu
    tags: ubuntu,apache2,apache,telnet
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - telnet
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php CentOS
    tags: centos,apache,httpd
    yum:
      name:
        - httpd
        - php
        - telnet
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd CentOS
    tags: centos,apache,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: change e-mail address for admin
    tags: centos,apache,httpd
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin fishbloke@hotmail.com
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: change e-mail address for admin
    tags: centos,apache,httpd
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin fishbloke@hotmail.com
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: restart httpd CentOS
    tags: apache,centos,httpd
    service: 
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy defualt html file for site
    tags: apache,apache2,https
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip
 
  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.1.9/terraform_1.1.9_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: db_servers
  become: true
  tasks:
 
  - name: install mariadb package CentOS
    tags: centos,db,mariadb,telnet
    yum:
      name: 
         - mariadb-server
         - telnet
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package Ubuntu
    tags: ubuntu,db,mariadb,telnet
    apt:
      name:
         - mariadb-server
         - telnet
      state: latest
    when: ansible_distribution == "Ubuntu"
